
spring:
  datasource:
    host: 127.0.0.1

    username: root
    password: 123456
  multi:
    datasource:
      primary:
        jdbc-url: jdbc:mysql://${spring.datasource.host:localhost}:3306/datasource1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
      secondary:
        jdbc-url: jdbc:mysql://${spring.datasource.host:localhost}:3306/datasource2?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.transaction.interceptor: TRACE