spring:
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://172.16.212.139:37017/test

  datasource:
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  # 是否启用 spring.flyway.
  flyway:
    enabled: false
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    table: flyway_schema_history
    encoding: UTF-8
    baseline-on-migrate: true
    baseline-version: 3
    check-location: false
    clean-on-validation-error: false
    # 在读元数据表时，是否忽略失败的后续迁移.
    ignore-failed-future-migration: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml





